enableGlobalCache: false

nodeLinker: node-modules

npmRegistryServer: "https://registry.yarnpkg.com"

npmScopes:
  brynlabs:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.foolsparadise.de"
  foolsparadise:
    npmAlwaysAuth: true
    npmRegistryServer: "https://npm.foolsparadise.de"

yarnPath: .yarn/releases/yarn-4.9.2.cjs
